version: "3.3"
services:
  app:
    build: .
    volumes:
      - ./:/opt/app
    command: scrapyd-deploy local
    env_file:
      - ./docker-compose.env
      - ./docker-compose.local.env
    depends_on:
      - scrapyd
    ports:
      - 8088:8088
  # scrapyd (used for managing, running and scheduling spiders)
  scrapyd:
    build: .
    volumes:
      - ./:/opt/app
    command: scrapyd --pidfile=/tmp/twisted.pid --logfile=-
    env_file:
      - ./docker-compose.env
      - ./docker-compose.local.env
    ports:
      - 6800:6800

