import scrapy

class MenuItems(scrapy.Item):

    csc = scrapy.Field()
    id = scrapy.Field()
    msi = scrapy.Field()
    nm = scrapy.Field()
    rt = scrapy.Field()
    pr = scrapy.Field()
    opr = scrapy.Field()
    idc = scrapy.Field()
    dc = scrapy.Field()
    ipm = scrapy.Field()
    exG = scrapy.Field()
    dsc = scrapy.Field()
    img = scrapy.Field()
    im = scrapy.Field()
    ht = scrapy.Field()
    isf = scrapy.Field()
    isi = scrapy.Field()
    ipr = scrapy.Field()
    icc = scrapy.Field()
    br = scrapy.Field()
    tagIds = scrapy.Field()
    imgurl = scrapy.Field()